name: .NET 8 CI

on:
  push:
    branches: ["**"]
  pull_request:

# Cancel superseded runs on the same branch/PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  SOLUTION_PATH: VpnToggle.sln
  PUBLISH_PROJECT: VpnToggle/VpnToggle.csproj

jobs:
  build-test-publish:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          cache: true
          cache-dependency-path: |
            **/packages.lock.json
            **/*.csproj
            **/*.sln

      - name: Restore
        run: dotnet restore $env:SOLUTION_PATH

      - name: Build (Release)
        run: dotnet build $env:SOLUTION_PATH -c Release --no-restore -p:ContinuousIntegrationBuild=true

      - name: Test
        run: |
          if (Get-ChildItem -Recurse -Filter "*Tests.csproj") {
            dotnet test --no-build -c Release --logger "trx;LogFileName=test-results.trx"
          } else {
            Write-Host "No test projects found, skipping tests."
          }

      - name: Upload test results (if any)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: '**/TestResults/*.trx'
          retention-days: 7

      - name: Publish app (framework-dependent)
        run: dotnet publish $env:PUBLISH_PROJECT -c Release -o out --no-build

      - name: Upload artefact
        uses: actions/upload-artifact@v4
        with:
          name: VpnToggle-CI-${{ github.run_number }}
          path: out/**
          retention-days: 14
