name: .NET 8 Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  PROJECT_PATH: VpnToggle/VpnToggle.csproj
  RIDS: "win-x64 win-arm64"
  PUBLISH_PROPS: >
    -p:PublishSingleFile=true
    -p:SelfContained=true
    -p:PublishTrimmed=false
    -p:IncludeNativeLibrariesForSelfExtract=true
    -p:DebugType=None
    -p:TieredPGO=true
    -p:ReadyToRun=true

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          cache: true
          cache-dependency-path: |
            **/packages.lock.json
            **/*.csproj
            **/*.sln

      - name: Restore
        run: dotnet restore $env:PROJECT_PATH

      - name: Build (Release with version from tag)
        run: dotnet build $env:PROJECT_PATH -c Release --no-restore -p:ContinuousIntegrationBuild=true -p:Version=${{ github.ref_name }} -p:FileVersion=${{ github.ref_name }}

      - name: Publish per RID (self-contained single-file)
        run: |
          $version = $env:GITHUB_REF_NAME.TrimStart("v")
          $appname = "VpnToggle"
          New-Item -ItemType Directory -Force -Path dist | Out-Null
          foreach ($rid in $env:RIDS.Split(" ")) {
            $out = "publish-$rid"
            dotnet publish $env:PROJECT_PATH -c Release -r $rid $env:PUBLISH_PROPS -o $out --no-build
            Compress-Archive -Path "$out/*" -DestinationPath "dist/${appname}-$version-$rid.zip" -Force
          }

      - name: Generate SHA256 checksums
        run: |
          Set-Location dist
          Get-ChildItem *.zip | ForEach-Object {
            $hash = Get-FileHash $_.FullName -Algorithm SHA256
            "$($hash.Hash)  $($_.Name)" | Out-File -Append -FilePath SHA256SUMS.txt
          }

      - name: Create/Update GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            dist/*.zip
            dist/SHA256SUMS.txt
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
