name: .NET 8 Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  PROJECT_PATH: VpnToggle/VpnToggle.csproj
  RIDS: "win-x64"
  PUBLISH_PROPS: >
    -p:PublishSingleFile=true
    -p:SelfContained=true
    -p:PublishTrimmed=false
    -p:IncludeNativeLibrariesForSelfExtract=true
    -p:DebugType=None
    -p:TieredPGO=true
    -p:ReadyToRun=true

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout (exact tag)
        uses: actions/checkout@v4
        with:
            ref: ${{ github.ref }}   # checkout the tag that triggered the run
            fetch-depth: 0           # full history incl. tags; avoids ref collisions


      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          cache: true
          cache-dependency-path: |
            **/packages.lock.json
            **/*.csproj
            **/*.sln

      - name: Restore
        run: dotnet restore $env:PROJECT_PATH

      - name: Build (Release with version from tag)
        run: |
            $ver = "${{ github.ref_name }}".TrimStart("v")   # e.g. v1.0.2 -> 1.0.2
            dotnet build $env:PROJECT_PATH -c Release --no-restore `
              -p:ContinuousIntegrationBuild=true `
              -p:Version=$ver `
              -p:AssemblyVersion=$ver `
              -p:FileVersion=$ver `
              -p:InformationalVersion=${{ github.ref_name }}

      - name: Publish per RID (self-contained single-file)
        run: |
          $version = $env:GITHUB_REF_NAME.TrimStart("v")
          $appname = "VpnToggle"
          New-Item -ItemType Directory -Force -Path dist | Out-Null
          foreach ($rid in $env:RIDS.Split(" ")) {
            $out = "publish-$rid"
            dotnet publish $env:PROJECT_PATH -c Release -r $rid $env:PUBLISH_PROPS -o $out --no-build
            Compress-Archive -Path "$out/*" -DestinationPath "dist/${appname}-$version-$rid.zip" -Force
          }

      - name: Generate SHA256 checksums
        run: |
          Set-Location dist
          Get-ChildItem *.zip | ForEach-Object {
            $hash = Get-FileHash $_.FullName -Algorithm SHA256
            "$($hash.Hash)  $($_.Name)" | Out-File -Append -FilePath SHA256SUMS.txt
          }

      # Publish x64 to repo-root publish\win-x64 (no profile)
      - name: Publish x64 for installer
        run: |
          $props = @(
            '-p:PublishSingleFile=true',
            '-p:SelfContained=true',
            '-p:PublishTrimmed=false',
            '-p:IncludeNativeLibrariesForSelfExtract=true',
            '-p:DebugType=None',
            '-p:TieredPGO=true',
            '-p:ReadyToRun=true'
          )
          New-Item -ItemType Directory -Force -Path "publish\win-x64" | Out-Null
          dotnet publish $env:PROJECT_PATH -c Release -r win-x64 @props -o "publish\win-x64"


      - name: Install Inno Setup
        run: choco install innosetup --yes

      - name: Build installer
        run: |
          $ver = "${{ github.ref_name }}".TrimStart("v")
          iscc.exe /DMyVersion=$ver VpnToggleInstaller.iss

      - name: Create/Update GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            dist/*.zip
            dist/SHA256SUMS.txt
            output/VpnToggle-Setup.exe 
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
